name: volga
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  get_it: ^7.2.0
  dio: ^4.0.3
  equatable: ^2.0.3
  auto_route: ^3.1.3
  percent_indicator: ^3.4.0
  sliding_up_panel: ^2.0.0+1
  logger: ^1.1.0
  json_annotation: ^4.3.0
  image_picker: ^0.8.4+4
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.1.1
  flutter_native_splash: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  auto_route_generator: ^3.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

  assets:
    - assets/icons/
    - assets/images/

